language: node_js
node_js:
  - "6"
before_install:
  - git config --global push.default matching
  - git config --global user.name "erguotou"
  - git config --global user.email "erguotou525@gmail.com"
install:
  - npm install -g vue-cli
  - npm install
  - node test/index.js
script:
  - cd ../test-fullstack
  - npm install
  - npm run lint
  - npm run build
cache:
  directories:
    - node_modules
    - $(npm config get prefix)/vue-cli
